name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_project:
    raw_deals:
      +column_types:
        closed_date: string
        created_date: string

models:
  dbt_project:
    staging:
      +materialized: table
    mart:
      +materialized: table